name: black
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: RojerGS/python-black-check@master
        with:
          line-length: '88'
          path: '.'
